baseurl = "/"
title = "data+science"
theme = "hugo-theme-console"
languageCode = "en-us"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", #"_files$",
               "\\.knit\\.md$", "\\.utf8\\.md$"]

#[permalinks]
#  posts = "/:title/"

[params]
  # highlightjsVersion = "10.0.2"
  # highlightjsCDN = "//cdnjs.cloudflare.com"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "tomorrow"
  
  [[params.navlinks]]
  name = "about/"
  url = "about/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"
  
  [[params.navlinks]]
  name = "resources/"
  url = "resources/"
  
  [[params.navlinks]]
  name = "tags/"
  url = "tags/"

#[markup]
#  [markup.highlight]
#    style = "tomorrow"