baseURL = "/"
languageCode = "en-us"
title = "data+science"
theme="archie"
copyright = "© Athul"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[[menu.main]]
name = "Posts"
url = "/post"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

#[[params.social]]
[[menu.main]]
name = "GitHub"
#icon = "github"
url = "https://github.com/sxmorgan"
weight = 4