baseURL = "/"
languageCode = "en-us"
title = "data+science"
theme="archie"
copyright = "© Athul"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/sxmorgan"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://github.com/sxmorgan_/"

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4